[package]
name = "riff-wave-reader"
version = "0.1.0"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"



[dependencies]
byteorder = "1.3"
thiserror = "1.0"

[workspace]
members = [
    ".",
    "cli"
]
default-members = [
    "cli",
]